# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{kuaiqian}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Yuanyi Zhang"]
  s.date = %q{2010-06-04}
  s.description = %q{A Ruby wrapper of Kauqian(快钱) Payment API}
  s.email = %q{zhangyuanyi@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "lib/generators/kuaiqian/kuaiqian_generator.rb",
     "lib/generators/kuaiqian/templates/kuaiqian.yml",
     "lib/kuaiqian.rb",
     "lib/kuaiqian/config.rb",
     "lib/kuaiqian/request.rb",
     "lib/kuaiqian/response.rb"
  ]
  s.homepage = %q{http://github.com/yzhang/kuaiqian}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A Ruby wrapper of Kauqian(快钱) Payment API}
  s.test_files = [
    "spec/request_spec.rb",
     "spec/response_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

